#!/bin/bash
#
# ci/scripts/shipit
#
# Script for generating Github release / tag assets
# and managing release notes for a BOSH Release pipeline
#
# author:  James Hunt <james@niftylogic.com>
# created: 2016-03-30

set -eu

if [[ -z ${VERSION_FROM} ]]; then
  echo >&2 "VERSION_FROM environment variable not set, or empty.  Did you misconfigure Concourse?"
  exit 2
fi
if [[ ! -f ${VERSION_FROM} ]]; then
  echo >&2 "Version file (${VERSION_FROM}) not found.  Did you misconfigure Concourse?"
  exit 2
fi
VERSION=$(cat ${VERSION_FROM})
if [[ -z ${VERSION} ]]; then
  echo >&2 "Version file (${VERSION_FROM}) was empty.  Did you misconfigure Concourse?"
  exit 2
fi

#if [[ ! -f bosh-release/ci/release_notes.md ]]; then
#  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
#  exit 1
#fi

###############################################################

cat > bosh-release/config/private.yml << EOF
---
blobstore:
  options:
    access_key_id: ${AWS_ACCESS_KEY}
    secret_access_key: ${AWS_SECRET_KEY}
EOF

export BOSH_CA_CERT=${BOSH_CA_CERT}
export BOSH_CLIENT=${BOSH_USERNAME}
export BOSH_CLIENT_SECRET=${BOSH_PASSWORD}

(cd bosh-release
 mkdir -p releases/${RELEASE_NAME2}/${RELEASE_NAME2}
 bosh -n create-release --tarball=releases/${RELEASE_NAME2}/${RELEASE_NAME2}-${VERSION}.tgz --version "${VERSION}" --final)


mkdir -p gh/artifacts
echo "v${VERSION}"                         > gh/tag
echo "${RELEASE_NAME} v${VERSION}"         > gh/name
#mv bosh-release/ci/release_notes.md          gh/notes.md
echo "Release ${RELEASE_NAME} v${VERSION}" > gh/notes.md
cp bosh-release/releases/${RELEASE_NAME2}/${RELEASE_NAME2}-${VERSION}.tgz  gh/artifacts

cat > gh/notification <<EOF
<!here> New ${RELEASE_NAME} v${VERSION} released!
EOF


# GIT!
git config --global user.name "CICD Robot"
git config --global user.email "cicd@oakton.digital"

(cd bosh-release
 git merge --no-edit ${BRANCH}
 git add -A
 git status
 git commit -m "release v${VERSION}")

# so that future steps in the pipeline can push our changes
cp -a bosh-release pushme

